factory/urls.py
# coding:utf-8
# from django.conf.urls import url
from django.urls import include, path
from factory.views import FactoryList, FactoryDetail, MachineDetail, MachineList
# from factory.views import FactoryList, FactoryDetail, CategoryList, MachineDetail

app_name = 'factory'
urlpatterns = [
    path("", FactoryList.as_view(), name="factory_list"),
    path("factory/<int:pk>", FactoryDetail.as_view(), name="factory_detail"),
    # path("category", CategoryList.as_view(), name="category_list"),
    path("machine", MachineList.as_view(), name="machine_list"),
    path("machine/<int:pk>", MachineDetail.as_view(), name="machine_detail"),
]

fill_factory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("auth/", include("allauth.urls")),
    path("", include('factory.urls', namespace="factory"))
]

factory/forms.py
import imp
from tkinter import Widget
from django import forms
from factory.models import Machine, MachineType, Maker
from django.db.models import fields


class SpecMixin(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        machine_fields = Machine._meta.get_fields()
        for f in machine_fields:
            if 'spec' in f.name:
                if type(f) in (fields.IntegerField, fields.FloatField):
                    self.fields[f'min_{f.name}'] = forms.IntegerField(
                        required=False, label=f'{f.verbose_name};最小値',
                        widget=forms.NumberInput(attrs={"class": "form-control"}),
                        )
                    self.fields[f'max_{f.name}'] = forms.IntegerField(
                        required=False, label=f'{f.verbose_name};最大値',
                        widget=forms.NumberInput(attrs={"class": "form-control"}),
                        )
                elif type(f) == fields.BooleanField:
                    self.fields[f"{f.name}"] = forms.BooleanField(
                        required=False, label=f.verbose_name,
                        )
                elif type(f) == fields.CharField:
                    self.fields[f"{f.name}"] = forms.CharField(
                        required=False, label=f.verbose_name,
                        widget=forms.TextInput(attrs={"class": "form-control"})
                        )


class MachineSearchForm(SpecMixin, forms.Form):
    machine_name = forms.CharField(
        label='機械名', required=False,
        widget=forms.TextInput(attrs={"class": "form-control"})
        )
    machine_types = forms.ModelMultipleChoiceField(
        queryset=MachineType.objects.all(), label='機械種別', required=False,
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
        )
    makers = forms.ModelMultipleChoiceField(
        queryset=Maker.objects.all(), label='メーカー', required=False,
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
        )


class FactorySearchForm(SpecMixin, forms.Form):
    factory_name = forms.CharField(
        label='工場名', required=False,
        widget=forms.TextInput(attrs={"class": "form-control"})
        )
    is_having_machines = forms.BooleanField(
        label="保有機械データあり", required=False,
        widget=forms.CheckboxInput()
    )
    machine_name = forms.CharField(
        label='機械名', required=False,
        widget=forms.TextInput(attrs={"class": "form-control"})
        )
    machine_types = forms.ModelMultipleChoiceField(
        queryset=MachineType.objects.all(), label='機械種別', required=False,
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
        )
    makers = forms.ModelMultipleChoiceField(
        queryset=Maker.objects.all(), label='メーカー', required=False,
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
        )

factory/views.py
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from factory.models import Factory, Machine, MachineType, OwnMachine, Maker
from factory.forms import FactorySearchForm, MachineSearchForm
from django.contrib import messages
from django.conf import settings
from django.db.models import fields


class FactoryList(ListView):
    model = Factory
    template_name = "factory_list.html"
    paginate_by = 20

    def get_context_data(self, *, object_list=None, **kwargs):
        # params
        params = ""
        params_dict = dict()
        search_form = FactorySearchForm(self.request.GET)
        for k, vs in dict(self.request.GET).items():
            if not k == "page":
                name = search_form.fields[k].label
                params_dict[name] = ",".join(vs)
                for v in vs:
                    params = params + "&{}={}".format(k, v)
        if params:
            messages.info(self.request, "検索結果を表示します。{}".format(params))
        # context
        context = super().get_context_data(**kwargs)
        context.update({
            "search_form": search_form,
            "num": self.get_queryset().count(),
            "params": params,
            "params_dict": params_dict,
            "specs": settings.SPECS,
        })
        return context

    def get_queryset(self):
        queryset = super(FactoryList, self).get_queryset()
        if self.request.GET: 
            machine_queryset = Machine.objects.all()
            machine_fields = Machine._meta.get_fields()
            is_query_with_machine = False
            # 工場名
            if self.request.GET.get("factory_name"):
                queryset = queryset.filter(name__icontains=self.request.GET.get("factory_name"))
            # 機械データあり
            if self.request.GET.get("is_having_machines"):
                is_query_with_machine = True
            # spec
            for f in machine_fields:
                if 'spec' in f.name:
                    if type(f) in (fields.IntegerField, fields.FloatField):
                        if self.request.GET.get(f"max_{f.name}"):
                            is_query_with_machine = True
                            machine_queryset = machine_queryset.filter(**{f'{f.name}__lte': self.request.GET.get(f"max_{f.name}")})
                        elif self.request.GET.get(f"min_{f.name}"):
                            is_query_with_machine = True
                            machine_queryset = machine_queryset.filter(**{f'{f.name}__gte': self.request.GET.get(f"min_{f.name}")})
                    elif type(f) == fields.BooleanField and self.request.GET.get(f.name):
                        val = True if self.request.GET.get(f.name) == 'on' else False
                        machine_queryset = machine_queryset.filter(**{f'{f.name}': val})
                    elif type(f) == fields.CharField and self.request.GET.get(f.name):
                        machine_queryset = machine_queryset.filter(**{f'{f.name}__icontains': self.request.GET.get(f.name)})
            # 機械名
            if self.request.GET.get("machine_name"):
                is_query_with_machine = True
                machine_queryset = machine_queryset.filter(name__icontains=self.request.GET.get("machine_name"))
            # 機械種別
            if self.request.GET.getlist("machine_types"):
                machine_queryset = machine_queryset.filter(machine_type__in=self.request.GET.getlist("machine_types"))
            # maker
            if self.request.GET.getlist("makers"):
                machine_queryset = machine_queryset.filter(maker__in=self.request.GET.getlist("makers"))
            # machines
            if is_query_with_machine:
                own_machines = OwnMachine.objects.filter(machine__pk__in=set([m.pk for m in machine_queryset]))
                queryset = queryset.filter(pk__in=set([om.factory.pk for om in own_machines]))
        return queryset.distinct().order_by("-last_updated_at")


class FactoryDetail(DetailView):
    model = Factory
    template_name = "factory_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['own_machines'] = OwnMachine.objects.filter(factory=context['object']).select_related('machine')
        return context


class MachineList(ListView):
    model = Machine
    template_name = "machine_list.html"
    paginate_by = 20

    def get_context_data(self, **kwargs):
        params = ""
        params_dict = {}
        search_form = MachineSearchForm(self.request.GET)
        for k, vs in dict(self.request.GET).items():
            if not k == "page":
                name = search_form.fields[k].label
                if k == 'machine_types':
                    params_dict[name] = ",".join([u.name for u in MachineType.objects.filter(pk__in=vs)])
                elif k == 'makers':
                    params_dict[name] = ",".join([u.name for u in Maker.objects.filter(pk__in=vs)])
                else:
                    params_dict[name] = ",".join(vs)
                for v in vs:
                    params = params + "&{}={}".format(k, v)
        # context
        context = super(MachineList, self).get_context_data(**kwargs)
        context.update({
            "search_form": search_form,
            "num": self.get_queryset().count(),
            "params": params,
            "params_dict": params_dict,
            "specs": settings.SPECS,
        })
        return context
    
    def get_queryset(self):
        queryset = super(MachineList, self).get_queryset()
        if self.request.GET: 
            machine_fields = Machine._meta.get_fields()
            # spec
            for f in machine_fields:
                if 'spec' in f.name:
                    if type(f) in (fields.IntegerField, fields.FloatField):
                        if self.request.GET.get(f"max_{f.name}"):
                            queryset = queryset.filter(**{f'{f.name}__lte': self.request.GET.get(f"max_{f.name}")})
                        elif self.request.GET.get(f"min_{f.name}"):
                            queryset = queryset.filter(**{f'{f.name}__gte': self.request.GET.get(f"min_{f.name}")})
                    elif type(f) == fields.BooleanField and self.request.GET.get(f.name):
                        val = True if self.request.GET.get(f.name) == 'on' else False
                        queryset = queryset.filter(**{f'{f.name}': val})
                    elif type(f) == fields.CharField and self.request.GET.get(f.name):
                        queryset = queryset.filter(**{f'{f.name}__icontains': self.request.GET.get(f.name)})
            # 機械名
            if self.request.GET.get("machine_name"):
                queryset = queryset.filter(name__icontains=self.request.GET.get("machine_name"))
            # 機械種別
            if self.request.GET.getlist("machine_types"):
                queryset = queryset.filter(machine_type__in=self.request.GET.getlist("machine_types"))
            # maker
            if self.request.GET.getlist("makers"):
                queryset = queryset.filter(maker__in=self.request.GET.getlist("makers"))
        return queryset.distinct().order_by("-last_updated_at")


class MachineDetail(DetailView):
    model = Machine
    template_name = "machine_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        fields = context['object']._meta.get_fields()
        specs = dict()
        context["specs"] = dict()
        for f in fields:
            if 'spec_' in f.name and f.value_from_object(context['object']):
                specs[f.name] = {
                    'name': f.verbose_name,
                    'value': f.value_from_object(context['object'])
                }
                for i in settings.SPECS:
                    if f"spec_{i}" in f.name and not i in context["specs"].keys():
                        context["specs"][i] = settings.SPECS[i]
        context['specdata'] = specs
        # context["specs"] = settings.SPECS
        return context

factory/templates/base.html
{% load static %}
{% load admin_urls %}
{% load django_bootstrap5 %}

<html>
  <head>
    <title>FiLL Factory ({% block title %}{% endblock %})</title>
    <!-- Required meta tags -->
<!--    <meta charset="utf-8">-->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
    <link rel="icon" href="{%static 'favicon.ico'%}">
    <link rel="stylesheet" href="{%static 'common.css'%}">
    <script src="https://kit.fontawesome.com/0e8797feee.js" crossorigin="anonymous"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    <script src="https://code.jquery.com/jquery-3.6.0.slim.js" integrity="sha256-HwWONEZrpuoh951cQD1ov2HUK5zA5DwJ1DNUXaM6FsY=" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light navbar-light navbar-toggleable-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <i class="fas fa-industry"></i>
          FiLL Factory
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li>
              <a class="dropdown-item" href="{%url 'factory:factory_list'%}">
                <i class="fas fa-list"></i>&nbsp;工場一覧
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{%url 'factory:machine_list'%}">
                <i class="fas fa-list"></i>&nbsp;機械一覧
              </a>
            </li>
          </ul>
          <!--other-->
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
                <i class="fas fa-user-circle"></i> {{request.user}}
              </a>
              <ul class="dropdown-menu dropdown-menu-lg-end">
                {% if request.user.is_superuser %}
                <li><a class="dropdown-item" href="{%url 'admin:index'%}">
                  <i class="fas fa-users-cog"></i> Admin
                </a></li>
                <li><hr class="dropdown-divider"></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                <li><a class="dropdown-item" href='/auth/logout'>
                  <i class="fas fa-sign-out-alt"></i> Log Out
                </a></li>
                {% comment %} <li><a class="dropdown-item" href="/auth/social/connections">
                  <i class="fab fa-google-plus-square"></i>&nbsp;Social Auth
                </a></li> {% endcomment %}
                {% else %}
                <li><a class="dropdown-item" href='/auth/login'>
                  <i class="fas fa-sign-in-alt"></i> Log In
                </a></li>
                {% endif %}
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <h1>{% block page-tilte%}{% endblock %}</h1>
    {% block body %}{% endblock %}
  </body>

  {% block js %}{% endblock %}
</html>

factory/templates/factory_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load mathfilters %}

{% block title %}
工場詳細
{% endblock %}

{% block page-title %}
工場詳細
{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h5>工場詳細</h5>
      <table class="table">
        <tr class="bg-info">
          <th>項目</th>
          <th>値</th>
        </tr>
        <tr>
          <th>No</th>
          <td>{{object.pk}}</td>
        </tr>
        <tr>
          <th>工場名</th>
          <td>{{object.name}}</td>
        </tr>
        <tr>
          <th>詳細</th>
          <td>{{object.detail |linebreaksbr}}</td>
        </tr>
        <tr>
          <th>住所</th>
          <td>
            {{object.postal_code| default:""}}
            {{object.address| default:""}}
          </td>
        </tr>
        <tr>
          <th>URL</th>
          <td>
            <a href="object.url">{{object.url}}</a>
          </td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td>{{object.phone_number}}</td>
        </tr>
        <tr>
          <th>FAX</th>
          <td>{{object.fax_number}}</td>
        </tr>
        <tr>
          <th>メール</th>
          <td>{{object.mail_address}}</td>
        </tr>
        <tr>
          <th>作成日</th>
          <td>{{object.created_at}}</td>
        </tr>
        <tr>
          <th>更新日</th>
          <td>{{object.last_updated_at}}</td>
        </tr>
      </table>

      <h5>保有機械</h5>
      <table class="table">
        <tr class="bg-info">
          <th>No</th>
          <th>機械名</th>
          <th>機械種別</th>
          <th>メーカー</th>
          <th>保有数</th>
        </tr>
        {% for om in own_machines %}
        <tr>
          <td>
            <a href="{% url 'factory:machine_detail' pk=om.machine.pk %}">{{om.machine.pk}}</a>
          </td>
          <td>{{om.machine.name}}</td>
          <td>{{om.machine.machine_type.name}}</td>
          <td>{{om.machine.maker.name}}</td>
          <td>{{om.num}}</td>
        </tr>
        {% empty %}
        <tr><td colspan=5>No data</td></tr>
        {% endfor %}
      </table>
      <a href="{% url 'factory:factory_list' %}" class="btn btn-secondary">
        <i class="fas fa-arrow-circle-left"></i>&nbsp;一覧へ戻る
      </a>
    </div>
  </div>
</div>
{% endblock %}

factory/templates/machine_detail.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load mathfilters %}

{% block title %}
機械詳細
{% endblock %}

{% block page-title %}
機械詳細
{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <h5>機械詳細</h5>
      <table class="table">
        <tr class="bg-info">
          <th>項目</th>
          <th>値</th>
        </tr>
        <tr>
          <th>No</th>
          <td>{{object.pk}}</td>
        </tr>
        <tr>
          <th>機械名</th>
          <td>{{object.name}}</td>
        </tr>
        <tr>
          <th>種別</th>
          <td>{{object.machine_type.name}}</td>
        </tr>
        <tr>
          <th>詳細</th>
          <td>{{object.detail |default:'' |linebreaksbr}}</td>
        </tr>
        <tr>
          <th>作成日</th>
          <td>{{object.created_at}}</td>
        </tr>
        <tr>
          <th>更新日</th>
          <td>{{object.last_updated_at}}</td>
        </tr>
      </table>
      <h5>機械スペック</h5>
      <div class="accordion" id="accordion_spec">
        {% for k,v in specs.items %}
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingOne">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#{{k}}" aria-expanded="false" aria-controls="{{k}}">
              {{v}}
            </button>
          </h2>
          <div id="{{k}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordion_spec">
            <div class="accordion-body">
              <table class='table'>
                {% for sk, sv in specdata.items %}
                {% if 'spec_'|add:k in sk and sv.value %}
                <tr>
                  <th>{{sv.name}}</th>
                  <td>{{sv.value}}</td>
                </tr>
                {% endif %}
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
        {% empty %}
        詳細データなし
        {% endfor %}
      </div>

      <hr>
      <h5>保有工場</h5>
      <table class="table">
        <tr class="bg-info">
          <th>工場名</th>
          <th>都道府県</th>
          <th>保有数</th>
      <tr>
      {% for om in object.ownmachine_set.all %}
      <tr>
        <td>
          <a href="{%url 'factory:factory_detail' pk=om.factory.pk%}">
            {{om.factory}}
          </a>
        </td>
        <td>{{om.factory.prefecture}}</td>
        <td>{{om.num}}</td>
      </tr>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

factory/templates/machine_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load mathfilters %}

{% block title %}
機械一覧
{% endblock %}

{% block page-title %}
機械一覧
{% endblock %}


{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">
            機械一覧（{{num}}件）
          </button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link" id="filter-tab" data-bs-toggle="tab" data-bs-target="#filter" type="button" role="tab" aria-controls="filter" aria-selected="false">検索</button>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
          <div class="card">
            <div class="card-body table-responsive">
              <p>
                {% for k, v in params_dict.items %}
                {% if not v == "" %}
                <label class="badge {%if k == 'order_by'%}bg-warning{%else%}bg-info{%endif%} text-black">
                  {{k}}: {{v}}
                </label>
                {% endif %}
                {% endfor %}
              </p>
              <table class="table">
                <tr class="bg-info">
                  <th>No</th>
                  <th>機械名</th>
                  <th>機械種別</th>
                </tr>
                {% for object in object_list %}
                <tr>
                  <td>
                    <a href="{% url 'factory:machine_detail' pk=object.pk %}">{{object.pk}}</a>
                  </td>
                  <td>{{object.name}}</td>
                  <td>{{object.machine_type.name}}</td>
                </tr>
                {% empty %}
                <tr>
                  <td>該当なし</td>
                </tr>
                {% endfor %}
              </table>
            </div>
            <div class="card-footer">
              {% if page_obj.has_other_pages %}
              <nav>
                <ul class="pagination">
                  <!--previous-->
                  {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link"
                      href="{%url 'factory:machine_list'%}?page={{page_obj.previous_page_number}}{{params}}"
                    >&laquo;</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled"><a class="page-link">&laquo;</a></li>
                  {% endif %}
                  <!--first-->
                  {% if page_obj.number|sub:5 > 0 %}
                  <li class="page-item">
                    <a class="page-link"
                      href="{%url 'factory:machine_list'%}?page=1{{params}}"
                    >1</a>
                  </li>
                  {% endif %}
                  <!--pages-->
                  {% for i in page_obj.paginator.page_range %}
                  {% if page_obj.number == i %}
                  <li class="page-item active">
                    <a class="page-link" href="#">{{i}}</a>
                  </li>
                  {% elif page_obj.number|sub:i < 5 and page_obj.number|sub:i > -5 %}
                  <li class="page-item">
                    <a class="page-link"
                      href="{%url 'factory:machine_list'%}?page={{i}}{{params}}"
                    >{{i}}</a>
                  </li>
                  {% elif page_obj.number|sub:i == 5 or page_obj.number|sub:i == -5 %}
                  <li class="disabled">
                    <a class="page-link text-secondary d-inline-block text-muted" href="#">・・・</a>
                  </li>
                  {% endif %}
                  {% endfor %}
                  <!--last-->
                  {% if not page_obj.number == page_obj.paginator.num_pages and page_obj.paginator.num_pages > 5%}
                  <li class="page-item">
                    <a class="page-link"
                      href="{%url 'factory:machine_list'%}?page={{page_obj.paginator.num_pages}}{{params}}"
                    >{{page_obj.paginator.num_pages}}</a>
                  </li>
                  {% endif %}
                  <!--next-->
                  {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link"
                      href="{%url 'factory:machine_list'%}?page={{page_obj.next_page_number}}{{params}}"
                    >&raquo;</a>
                  </li>
                  {% else %}
                  <li class="page-item disabled"><a class="page-link">&raquo;</a></li>
                  {% endif %}
                </ul>
              </nav>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="filter" role="tabpanel" aria-labelledby="filter-tab">
          <div class="card">
            <form class="form" method="GET" id='searchForm'>
              <div class="card-body table-responsive">
                {% for f in search_form %}
                {% if not 'spec_' in f.name %}
                <p>
                  {{f.label}}
                  {{f}}
                </p>
                {% endif %}
                {% endfor %}
                <h5>機械スペック</h5>
                <div class="accordion" id="accordion_spec">
                  {% for k,v in specs.items %}
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#{{k}}" aria-expanded="false" aria-controls="{{k}}">
                        {{v}}
                      </button>
                    </h2>
                    <div id="{{k}}" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordion_spec">
                      <div class="accordion-body">
                        {% for f in search_form %}
                        {% if 'spec_'|add:k in f.name %}
                        <p>
                          {{f.label}}
                          {{f}}
                        </p>
                        {% endif %}
                        {% endfor %}
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
                <button type="submit" class="btn btn-sm btn-primary" id='submit'>
                  <i class="fas fa-search"></i>&nbsp;検索
                </button>
                <a href="{% url 'factory:factory_list' %}" class="btn btn-sm btn-secondary">
                  <i class="fas fa-undo"></i>&nbsp;クリア
                </a>
              </div>
            </form>
          </div>
        </div>
      </div>
      
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
  $('form#searchForm').submit(function() {
    $(':input', this).each(function() {
        this.disabled = !($(this).val());
    });
  });
</script>
{% endblock %}